name: New Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    name: Hello
    if: github.repository_owner == 'npm'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      {{> stepHello }}
