name: Post Dependabot

on:
  pull_request

permissions:
  contents: write

jobs:
  post-pr-test:
    {{> job
      jobName="post-pr-test"
      jobCheckout=(obj ref="${{ github.event.pull_request.head.sha }}")
    }}
      - name: Git status
        run: git status
