name: Release Integration

on:
  workflow_call:

jobs:
  check-registry:
    name: Check Registry
    if: {{{ ifOrg }}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: View in Registry
        run: echo "all good"
